### ISSUE TITLE
Specify what user account to use for SG appliance remote login

### ISSUE THREAD

**Issue by midwest-lab** [NetAppDocs/e-series-santricity-116#4]
Page: [Allow remote login](https://docs.netapp.com/us-en/e-series-santricity-116/sm-hardware/allow-remote-login.html)

For remote access to a SG node, once SSH is enabled you need to use the 'diag' user account.  This isn't specified anywhere and may help save users time in the future if we note this on our documentation.

**Comment by netapp-jolieg** [comment]
Hi, thanks for the feedback.
I will double-check with the Engineering team, and will then update the document accordingly.
Jolie

**Comment by netapp-jolieg** [comment]
Hello. 
I consulted with our Engineering team and they recommended that we do NOT publish the user account name. The customer should be working with the Tech Support team during this procedure.
Thanks,
Jolie
